-- Generated by the build: the minimap tiles of Alterac Valley (world map 30) in this folder, as column_row.
-- It sits beside the tiles on purpose: without this folder the list is not loaded either,
-- and the minimap keeps the game's own terrain there.
local ADDON, ns = ...

ns.minimapTiles = ns.minimapTiles or {}
ns.minimapTiles[30] = {
    ["30_29"] = true, ["30_30"] = true, ["30_31"] = true, ["30_32"] = true, ["30_33"] = true, ["30_34"] = true, ["30_35"] = true, ["31_29"] = true, ["31_30"] = true, ["31_31"] = true,
    ["31_32"] = true, ["31_33"] = true, ["31_34"] = true, ["31_35"] = true, ["32_29"] = true, ["32_30"] = true, ["32_31"] = true, ["32_32"] = true, ["32_33"] = true, ["32_34"] = true,
    ["32_35"] = true, ["33_29"] = true, ["33_30"] = true, ["33_31"] = true, ["33_32"] = true, ["33_33"] = true, ["33_34"] = true, ["33_35"] = true, ["34_29"] = true, ["34_30"] = true,
    ["34_31"] = true, ["34_32"] = true, ["34_33"] = true, ["34_34"] = true, ["34_35"] = true,
}
