"""Write DenoMap/Manifest.lua: the file ids that have an upscale in Maps/, each with the width
in pixels of the game's own file (a quarter of ours)."""
import os, struct
D = ".."
have = sorted(int(f[:-4]) for f in os.listdir(D + "/Maps") if f.endswith(".blp"))
def native(file_id):
    with open(f"{D}/Maps/{file_id}.blp", "rb") as f:
        return max(1, struct.unpack("<I", f.read(16)[12:16])[0] // 4)
with open(D + "/Manifest.lua", "w", encoding="utf-8", newline="\n") as f:
    f.write("-- Generated by the build: every file id that has a 4x upscale in Maps, and the width in\n")
    f.write("-- pixels of the game's own file.\n")
    f.write("local ADDON, ns = ...\n\nns.files = {\n")
    for i in range(0, len(have), 8):
        f.write("    " + " ".join(f"[{x}] = {native(x)}," for x in have[i:i + 8]) + "\n")
    f.write("}\n")
print("manifest", len(have))
