"""Write DenoMap/Manifest.lua: the file ids that have an upscale in Maps/."""
import json, os
D = '..'
have = sorted(int(f[:-4]) for f in os.listdir(D + '/Maps') if f.endswith('.blp'))
want = have
with open(D + '/Manifest.lua', 'w', encoding='utf-8', newline='\n') as f:
    f.write('-- Generated by the build: every file id that has a 4x upscale in Maps.\n')
    f.write('local ADDON, ns = ...\n\nns.files = {\n')
    for i in range(0, len(have), 8):
        f.write('    ' + ' '.join(f'[{x}] = true,' for x in have[i:i + 8]) + '\n')
    f.write('}\n')
print('manifest', len(have), 'of', len(want))
