"""Write ../Minimap/<world map id>/Tiles.lua for every world in mjobs.json."""
import json, os

J = json.load(open('mjobs.json'))
for m, tiles in J.items():
    os.makedirs(f'../Minimap/{m}', exist_ok=True)
    keys = sorted(tiles, key=lambda k: tuple(map(int, k.split('_'))))
    lines = [
        f'-- Generated by the build: the minimap tiles of world map {m} in this folder, as column_row.',
        'local ADDON, ns = ...',
        '',
        'ns.minimapTiles = ns.minimapTiles or {}',
        f'ns.minimapTiles[{m}] = {{',
    ]
    for i in range(0, len(keys), 10):
        lines.append('    ' + ' '.join(f'["{k}"] = true,' for k in keys[i:i + 10]))
    lines.append('}')
    with open(f'../Minimap/{m}/Tiles.lua', 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')
    print(m, len(tiles))
