-- Generated by the build: the minimap tiles of Warsong Gulch (world map 489) in this folder, as column_row.
-- It sits beside the tiles on purpose: without this folder the list is not loaded either,
-- and the minimap keeps the game's own terrain there.
local ADDON, ns = ...

ns.minimapTiles = ns.minimapTiles or {}
ns.minimapTiles[489] = {
    ["27_27"] = true, ["27_28"] = true, ["27_29"] = true, ["27_30"] = true, ["28_27"] = true, ["28_28"] = true, ["28_29"] = true, ["28_30"] = true, ["29_27"] = true, ["29_28"] = true,
    ["29_29"] = true, ["29_30"] = true, ["30_27"] = true, ["30_28"] = true, ["30_29"] = true, ["30_30"] = true,
}
