-- Generated by the build: the minimap tiles of Arathi Basin (world map 529) in this folder, as column_row.
-- It sits beside the tiles on purpose: without this folder the list is not loaded either,
-- and the minimap keeps the game's own terrain there.
local ADDON, ns = ...

ns.minimapTiles = ns.minimapTiles or {}
ns.minimapTiles[529] = {
    ["28_28"] = true, ["28_29"] = true, ["28_30"] = true, ["28_31"] = true, ["29_28"] = true, ["29_29"] = true, ["29_30"] = true, ["29_31"] = true, ["30_28"] = true, ["30_29"] = true,
    ["30_30"] = true, ["30_31"] = true, ["31_28"] = true, ["31_29"] = true, ["31_30"] = true, ["31_31"] = true,
}
