-- Generated by the build: the minimap tiles of Zephras Isle (world map 2991) in this folder, as column_row.
-- It sits beside the tiles on purpose: without this folder the list is not loaded either,
-- and the minimap keeps the game's own terrain there.
local ADDON, ns = ...

ns.minimapTiles = ns.minimapTiles or {}
ns.minimapTiles[2991] = {
    ["25_22"] = true, ["25_23"] = true, ["25_24"] = true, ["25_25"] = true, ["25_26"] = true, ["25_27"] = true, ["25_28"] = true, ["25_29"] = true, ["26_22"] = true, ["26_23"] = true,
    ["26_24"] = true, ["26_25"] = true, ["26_26"] = true, ["26_27"] = true, ["26_28"] = true, ["26_29"] = true, ["27_22"] = true, ["27_23"] = true, ["27_24"] = true, ["27_25"] = true,
    ["27_26"] = true, ["27_27"] = true, ["27_28"] = true, ["27_29"] = true, ["28_22"] = true, ["28_23"] = true, ["28_24"] = true, ["28_25"] = true, ["28_26"] = true, ["28_27"] = true,
    ["28_28"] = true, ["28_29"] = true, ["29_22"] = true, ["29_23"] = true, ["29_24"] = true, ["29_25"] = true, ["29_26"] = true, ["29_27"] = true, ["29_28"] = true, ["29_29"] = true,
    ["30_22"] = true, ["30_23"] = true, ["30_24"] = true, ["30_25"] = true, ["30_26"] = true, ["30_27"] = true, ["30_28"] = true, ["30_29"] = true, ["31_22"] = true, ["31_23"] = true,
    ["31_24"] = true, ["31_25"] = true, ["31_26"] = true, ["31_27"] = true, ["31_28"] = true, ["31_29"] = true, ["32_22"] = true, ["32_23"] = true, ["32_24"] = true, ["32_25"] = true,
    ["32_26"] = true, ["32_27"] = true, ["32_28"] = true, ["32_29"] = true, ["33_22"] = true, ["33_23"] = true, ["33_24"] = true, ["33_25"] = true, ["33_26"] = true, ["33_27"] = true,
    ["33_28"] = true, ["33_29"] = true,
}
