-- Generated by the build: the minimap tiles of Darkspear Islands (world map 2997) in this folder, as column_row.
-- It sits beside the tiles on purpose: without this folder the list is not loaded either,
-- and the minimap keeps the game's own terrain there.
local ADDON, ns = ...

ns.minimapTiles = ns.minimapTiles or {}
ns.minimapTiles[2997] = {
    ["26_30"] = true, ["26_31"] = true, ["26_32"] = true, ["26_33"] = true, ["26_34"] = true, ["27_30"] = true, ["27_31"] = true, ["27_32"] = true, ["27_33"] = true, ["27_34"] = true,
    ["28_30"] = true, ["28_31"] = true, ["28_32"] = true, ["28_33"] = true, ["28_34"] = true, ["29_30"] = true, ["29_31"] = true, ["29_32"] = true, ["29_33"] = true, ["29_34"] = true,
    ["30_30"] = true, ["30_31"] = true, ["30_32"] = true, ["30_33"] = true, ["30_34"] = true,
}
