"""Write DenoMap/Manifest.lua: the file ids that have an upscale in Maps/."""
import json, os
D = '..'
J = json.load(open('jobs.json'))
want = sorted({t[2] for a in J.values() for t in a['tiles']} |
              {t[2] for a in J.values() for o in a['overlays'].values() for t in o['tiles']})
have = [f for f in want if os.path.exists(f'{D}/Maps/{f}.blp')]
with open(D + '/Manifest.lua', 'w', encoding='utf-8', newline='\n') as f:
    f.write('-- Generated by the build: every file id that has a 4x upscale in Maps.\n')
    f.write('local ADDON, ns = ...\n\nns.files = {\n')
    for i in range(0, len(have), 8):
        f.write('    ' + ' '.join(f'[{x}] = true,' for x in have[i:i + 8]) + '\n')
    f.write('}\n')
print('manifest', len(have), 'of', len(want))
